"""empty message

Revision ID: 1101d079b3c4
Revises: None
Create Date: 2015-07-02 17:07:26.043540

"""

# revision identifiers, used by Alembic.
revision = '1101d079b3c4'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('pedagogy', sa.String(length=64), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('thread', sa.String(length=64), nullable=True),
    sa.Column('theme', sa.String(length=64), nullable=True),
    sa.Column('integrated_course', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('theme_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('theme', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thread_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('thread', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verbs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=32), nullable=True),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('taxonomy', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('member_since', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('learning_objectives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('who', sa.String(length=64), nullable=True),
    sa.Column('verb', sa.String(length=32), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('free_form_version', sa.Text(), nullable=True),
    sa.Column('taxonomy', sa.String(length=64), nullable=True),
    sa.Column('integrated_course', sa.String(length=64), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('thread_id', sa.Integer(), nullable=True),
    sa.Column('theme_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['theme_id'], ['theme_goals.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['thread_goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('stem', sa.Text(), nullable=True),
    sa.Column('correct_response', sa.String(length=128), nullable=True),
    sa.Column('distractor_1', sa.String(length=128), nullable=True),
    sa.Column('distractor_2', sa.String(length=128), nullable=True),
    sa.Column('distractor_3', sa.String(length=128), nullable=True),
    sa.Column('image_url', sa.String(length=128), nullable=True),
    sa.Column('learning_objective_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('integrated_course', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['learning_objective_id'], ['learning_objectives.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('test_new')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_new',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=40), autoincrement=False, nullable=True)
    )
    op.drop_table('questions')
    op.drop_table('learning_objectives')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('verbs')
    op.drop_table('thread_goals')
    op.drop_table('theme_goals')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_table('roles')
    ### end Alembic commands ###
